### ISSUE TITLE
Popover arrow origination point should not use margin in calculations

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#205] opened 2018-08-22 19:52 UTC
Popover arrows originate from the center of an element, including its margin as part of the element. I assume this is unintentional and that it should only include padding and border in the calculation of element height.

![image](https://user-images.githubusercontent.com/6835891/44487092-5b433f00-a623-11e8-86e5-e3341f788d79.png)

**Comment by diegohaz** [comment] 2018-08-22 19:57
That's not what should happen, indeed.

Could you please provide the code to reproduce it?

**Comment by Slapbox** [comment] 2018-08-22 20:01
@diegohaz here's (I believe) all the necessary code. The icon is a Font-Awesome icon.

```js
<Popover.Container>
  {popover => (
    <InlineBlock relative>
      <Base
        as={Popover.Toggle}
        aria-hidden="true"
        className="fa fa-list-alt"
        {...popover}
      />
      <Popover placement="left-end" fade slide expand hideOnClickOutside {...popover}>
        <Popover.Arrow />
        <MyContent />
      </Popover>
    </InlineBlock>
  )}
</Popover.Container>
```

```css
 button {
    margin-bottom: 18px;
    font-size: 24px !important;
    background: none;
}
```

**Comment by Slapbox** [comment] 2018-08-22 20:03
Just did a quick test and confirmed this occurs with plain text as content instead of a Font-Awesome icon.

**Comment by diegohaz** [comment] 2018-08-22 20:11
That happens because the `reference` element for Popover is its parent. You should whether apply the margin to `InlineBlock` or make `Popover` a child of `Button`.

**Comment by diegohaz** [comment] 2018-08-22 21:56
I'm gonna close this for now. 

But feel free to submit a PR proposing changes on the docs. As library authors, we know how the things work. It's hard to write proper documentation for those who don't. Usually, it results in unnecessary information or lack of it. That's why PRs improving documentation are so welcome. ❤️

**Closed by diegohaz** 2018-08-22 21:56 UTC
Labels: docs

**Comment by Slapbox** [comment] 2018-08-22 22:29
I can certainly relate to that. Thanks for your advice!

I'll try to give this method a try and report back if I have any trouble with it.

**Comment by Slapbox** [comment] 2018-11-02 23:53
@diegohaz this is pretty inconvenient because if I want my button to use opacity, that means the menu will be translucent, because the user has to stop hovering the button to use the menu. The other alternative is to have the arrow not line up. I've tried everything to make this work.

**Comment by diegohaz** [comment] 2018-11-03 00:31
@Slapbox I don't know if I got what you mean.

Anyways, I'm planning a revisit on Popover for v0.17.0 so you can pass another component as its reference:
```jsx
const ref = React.createRef();
<Button ref={ref} />
<Popover relativeTo={ref} />
```

**Comment by Slapbox** [comment] 2018-11-03 00:33
If you have a button that's say, `opacity: .3` until hovered, and then it's `opacity: 1`, if the popover is a child of the button it will be `opacity: .3` because the button is not being hovered while the popover is hovered. Does that make sense?

**Comment by diegohaz** [comment] 2018-11-03 00:40
If one is a child of another, hovering Popover should also hover the button.

Either way, you can just put them in a common relative parent. See the examples on https://reakit.io/components/popover
