### ISSUE TITLE
Content don`t scroll inside Dialog component. 

### ISSUE THREAD

**Issue by zarabotaet** [reakit/reakit#594] opened 2020-03-02 19:33 UTC
### Current behavior

Content don`t scroll inside Dialog component, on mobile (IOS, Safari or Chrome), when modal prop is true.

### Steps to reproduce the bug

[work](https://codesandbox.io/s/focused-sun-gmmhq)
[dont](https://codesandbox.io/s/naughty-wilbur-rq9dd)

**Comment by diegohaz** [comment] 2020-03-02 19:44
Duplicate of #469

**Closed by diegohaz** 2020-03-02 19:44 UTC
Labels: duplicate
