### ISSUE TITLE
Tippy tooltip (powered by popper.js) teleports to top left of TabList element when changing visible tabs

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#447] opened 2019-09-24 20:53 UTC
### Current behavior

When changing tabs, programmatically opened [Tippy](https://github.com/atomiks/tippy.js-react) tooltips are teleported to the very top left of the TabList element briefly before disappearing. 

I know Reakit has built in tooltips, but we're already a long ways down this road.

More importantly, `Tippy` uses `popper.js` so presumably this affects any implementation using `popper.js`

### Steps to reproduce the bug

_To be provided later_

### Expected behavior

In `v0` the tooltip would properly be immediately hidden when the tab it was a child of was hidden by activating another tab.

### Possible solutions

Presumably there's a good reason for the changes to how hidden content works in `reakit@v1`, but this issue did not exist in `v0` so perhaps there could be some clues there?

### Environment

```sh
$ npx envinfo --system --binaries --npmPackages

  System:
    OS: Windows 7
    CPU: (2) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    Memory: 5.09 GB / 13.75 GB
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Users\Remie\AppData\Roaming\npm\npm.CMD
```

**Comment by diegohaz** [comment] 2019-11-20 16:54
Closing this issue as we couldn't reproduce it. Please, if the problem persists and you can find a way to reproduce it, let me know and I'll reopen the issue.

**Closed by diegohaz** 2019-11-20 16:54 UTC
Labels: can't reproduce
