### ISSUE TITLE
Move styled-components to peerDependencies?

### ISSUE THREAD

**Issue by madiodio** [reakit/reakit#180] opened 2018-08-07 17:42 UTC
From jxnblk/grid-styled#88, I think that it would help prevent a category of bugs from happening if `styled-components` was resolved as devDependency and also mentioned as a peerDependency rather than a direct dependency. It will also help to reduce the bundle size following #170 #171 and #173. Thoughts?

**Comment by diegohaz** [comment] 2018-08-07 18:02
Hey, @madiodio. Thank you for coming up with this.

This was already suggested before here: https://github.com/styled-components/styled-components/issues/1676#issuecomment-380474497 (turned out that it was a different problem)

Particularly, I don't like the idea of putting it into peer dependencies and forcing the user to `npm install` it. If conflicts happen, I'd try to solve it by tweaking the `styled-components` version on package.json or yarn.lock first.

But, if making it a peer dependency is the only (or the best) solution for a future problem, we'll do that.

**Comment by madiodio** [comment] 2018-08-07 21:43
@diegohaz Thanks for your prompt reaction.

You're right about the hassle you might cause to users by forcing them to install another dependency to use this lib and after further reading through the docs I realized we already have a `styled` utility which makes even more complex to tackle this issue.

So maybe keeping this issue opened while we come up with a better solution will be a good compromise.

**Comment by codyaverett** [comment] 2019-02-05 19:14
@diegohaz I have an issue related to this.  

Trying to use `jest-styled-components` to get better feedback on snapshot tests, but it doesn't play well with Reakit in my CRA project.

Since I'm using `styled` through reakit I don't have styled components as a direct dependency in my app and `jest-styled-components` breaks when referenced.

e.g.     ```Cannot find module 'styled-components' from 'utils.js'```

Installing `styled-components` as a dependency in my project would cause a duplicate definition.
https://www.styled-components.com/docs/faqs#running-multiple-applications-on-one-page

The webpack vendoring isn't available to me unless I eject or rewire in a config.


Thoughts?

**Comment by diegohaz** [comment] 2019-02-05 19:32
@codyaverett Could you install styled-components and run the following commands?
```
yarn why reakit && yarn why styled-components
```

**Comment by diegohaz** [comment] 2019-02-05 21:41
Alright. You have two different versions of sc, v3 and v4. Reakit v0.15 only supports v3 (v0.16 supports v4, but it's still in beta).

I guess you should `npm install styled-components@3.4.10` to fix the issue.

**Comment by codyaverett** [comment] 2019-02-05 21:49
Good point, I didn't think about that!
Thanks for the help @diegohaz

**Comment by joshball** [comment] 2019-03-06 18:03
Hey @diegohaz , 

First, thank you for your insightful article on the [Single Element Patter](https://medium.freecodecamp.org/introducing-the-single-element-pattern-dfbd2c295c5d)n and creating this library. I am quite new to **_front-end_** development, so I find it intriguing how you all are managing and creating patterns around this space. 

At any rate, I am using [`Fannypack`](https://fannypack.style/primitives#inlineflex) which is based on `Reakit`. 

I was having problems with Typescript `types` and the dependencies and sent in a [pull request on some peer dependencies for types](https://github.com/fannypackui/fannypack/pull/58)
 
Following that issue, I noticed `Fannypack` had a hard `dependency` on:

> `"@types/styled-components": "4.1.8"`

Which of course brought me back to `Reakit`'s and I noticed the hard `dependency` on:

> `"styled-components": "^4.0.0",`

I also happened to notice I was getting continuous warnings in my project:
```
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.
See https://s-c.sh/2BAXzed for more info.
```
Which led me to comment in the PR:

> `Reakit` which depends on `styled-components` is looking problematic. As you are probably aware, `styled-components` does not like having multiple instances running:
> https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page
> But I think that `styled-components` (in `reakit`) maybe should be a peer? Which would allow you to pass the `styled-components` version on to the end user. What do you think? Should we ask `reakit` to make `styled-components` a `peerDependency`?

Now, back to my original, self-deprecating assertion: "I am quite new to **_front-end_** development" so I am not convinced I know the correct way to handle this, but it would seem to be that we might want to make `styled-components` a `peerDependency`? And then simply put a note in the `README` installation to install both:

> `yarn add reakit styled-components` 
> And for typescript users:
> `yarn add -D @types/styled-components` 

I would love to know your thoughts here. 


Also, kind of related, I was curious about one other thing. Again, this question is out of complete lack of understanding of this space. I am still trying to figure out how to simply align a div to the right, so be gentle with me, as what I am about to ask might be absurd ;-),
However, it appears that `emotion` is a popular and quite similar alternative to `styled-components`?  Would it make sense (or even be possible) that a small abstraction layer could be written and you could `peerDependency` depend on either `styled `or `emotion`? 

You seem to have [abstracted your requirements from `styled-components`](https://github.com/reakit/reakit/blob/fd4c97ecf54934c6f4761771fa3a5e60fa3d73e6/packages/reakit/src/styled.ts
) here:
```
import styled, {
  css,  keyframes,  createGlobalStyle,  isStyledComponent,  ThemeConsumer,  ThemeProvider,
  withTheme,  ServerStyleSheet,  StyleSheetManager
} from "styled-components";
```
It appears that much of the API in emotion is similar, but I certainly have no real understanding how complex some of that functionality would be. At any rate, I am truly interested in your thoughts on all of this more than I am about actually asking this to be done. Trade-off's are fascinating. ;-)

Thanks again.

**Comment by diegohaz** [comment] 2019-03-07 14:37
Hey @joshball. Thank you for the feedback.

Could you please run `yarn why styled-components` (or an equivalent command on npm) on your project? It's gonna show the versions of the package and why it's installed (which packages depend on it).

Since we're depending on `^4.0.0`, the version should be resolved to whatever the user has installed as long as it is 4.x.x. It doesn't always work as intended though. Removing the `node_modules` folder and the lock files should fix it. Otherwise, you can also use [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).

We're going to remove the dependency on styled-components for v1 so people can use any css library they want.

Regarding supporting emotion on v0. It's not possible without big breaking changes. We use the `css` helper a lot, and it's completely different between styled-components and emotion.

**Comment by joshball** [comment] 2019-03-08 17:24
Hey @diegohaz sorry for the delay:
```
=> Found "styled-components@4.1.3"
info Reasons this module exists
   - "_project_#@geo-ball#component-lib#reakit" depends on it
   - Hoisted from "_project_#@geo-ball#component-lib#reakit#styled-components"
```
Sounds good on the removal for v1. Out of curiosity, Is there a set of features or a timeline for v1 somewhere? It might be fun to help if I can.  
Thanks again.

**Comment by diegohaz** [comment] 2019-03-08 17:33
@joshball It seems that you have only one instance of styled-components. Does the problem persist?

About v1, I'm kind of rushing and experimenting things. [I tweeted about the main goals](https://twitter.com/diegohaz/status/1095013094579990529) to get some feedback. You can see some work in progress on the [next branch](https://github.com/reakit/reakit/tree/next). I'm gonna open a detailed issue soon.

To make the migration easier, I'm planning to expose a `reakit/next` path on `v0` (once v1 is officially released).
```js
import { Button } from "reakit";
import { Button as NextButton } from "reakit/next";
```

**Comment by diegohaz** [comment] 2019-04-11 18:47
Closing since styled-components dependency has been removed in v1.
Refer to #345

**Closed by diegohaz** 2019-04-11 18:47 UTC
Labels: breaking change, discussion
