### ISSUE TITLE
Flash of unstyled everything with 0.16.0

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#330] opened 2019-03-03 19:57 UTC
# Bug report

**What is the current behavior?**

In just on section of my app that relies on `Box` elements in a CSS grid, I get a flash of unstyled text, components, everything, before things show properly.

**If the current behavior is a bug, please provide the steps to reproduce.**

Unknown at this time how to reproduce. Maybe related to CSS grid. Not expecting a resolution at this time, just wanted to open a report

**What is the expected behavior?**

Components render with styles and there is no flash of unstyled

**Other relevant information:**
reakit version:  `0.16.0`

**Comment by mattfwood** [comment] 2019-03-12 13:46
Would you mind posting your `package.json` and possibly the source code to reproduce?

I ran into a similar bug a while ago and it was due to a conflict between my personal `styled-components` version and the `reakit` version.

Reakit will need to be at least version `0.16.0` to use styled-components V4.

**Comment by Slapbox** [comment] 2019-03-13 19:07
I can't share much, but I'm not using `styled-components` outside of `reakit.` I think I may be using `emotion` somewhere, which uses `styled-components` I believe. I don't think the flash of unstyled is related to that, but perhaps.

**From my `yarn.lock`**
```js
reakit@^0.16.0:
  version "0.16.0"
  resolved "https://registry.yarnpkg.com/reakit/-/reakit-0.16.0.tgz#1e7d1a539af749ae77cdacf6feedfe9bac6af5f9"
  integrity sha512-O7ouqjOPVUoZOx/dZ2ElswH/AnEHNJIzaXFM0WabyHOFXBGbXmHbeGTnMIrdKHe3e2scHgUW7H8WtBezSGkCMA==
  dependencies:
    "@emotion/is-prop-valid" "^0.7.3"
    constate "^0.9.0"
    popper.js "^1.14.7"
    prop-types "^15.6.2"
    reuse "^2.0.0"
    styled-components "^4.0.0"
    styled-selector "^0.1.1"
    styled-tools "^1.7.1"

styled-components@^4.0.0:
  version "4.1.3"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-4.1.3.tgz#4472447208e618b57e84deaaeb6acd34a5e0fe9b"
  integrity sha512-0quV4KnSfvq5iMtT0RzpMGl/Dg3XIxIxOl9eJpiqiq4SrAmR1l1DLzNpMzoy3DyzdXVDMJS2HzROnXscWA3SEw==
  dependencies:
    "@babel/helper-module-imports" "^7.0.0"
    "@emotion/is-prop-valid" "^0.7.3"
    "@emotion/unitless" "^0.7.0"
    babel-plugin-styled-components ">= 1"
    css-to-react-native "^2.2.2"
    memoize-one "^4.0.0"
    prop-types "^15.5.4"
    react-is "^16.6.0"
    stylis "^3.5.0"
    stylis-rule-sheet "^0.0.10"
    supports-color "^5.5.0"

```

**Comment by mattfwood** [comment] 2019-03-13 23:51
Hmm. The styled-components version and Reakit version look like they should match up, are you using some kind of server-side rendering such as NextJS?

**Comment by jeremija** [comment] 2019-03-15 07:27
I believe I encountered a similar issue. I'm using React's `renderToNodeStream` on the server-side. Is this supported?

**Comment by Slapbox** [comment] 2019-03-23 16:13
Nope no server side rendering, just locally rendered React. It's not the end of the world this bug. People may only see this outside of their browser in an Electron environment (or with server side rendering as @jeremija mentioned.)

**Comment by diegohaz** [comment] 2019-05-14 22:13
Cleaning up issues. Closing this as we can't reproduce it. If someone has this problem and can provide a reproduction, please open a new issue or comment here so we can find a solution.

**Closed by diegohaz** 2019-05-14 22:13 UTC
Labels: can't reproduce
