### ISSUE TITLE
Toolbar.Focusable failed test with RTL and Jest

### ISSUE THREAD

**Issue by luizcieslak** [reakit/reakit#337] opened 2019-03-14 13:53 UTC
# Bug report

**What is the current behavior?**

Can't create the renderer tree to make tests.

Error log:
```js
TypeError: _this.getElement(...).closest is not a function

      7 | describe('toolbar', () => {
      8 |   it('renders correctly', () => {
   > 9 |     const tree= renderer.create(<MyToolbar />).toJSON()
        |                          ^
     10 |     expect(tree).toMatchSnapshot()
     11 |   });
     12 | })

     at ToolbarFocusableComponent.getToolbar (node_modules/reakit/lib/Toolbar.js:110:44)
     at ToolbarFocusableComponent.getFocusables (node_modules/reakit/lib/Toolbar.js:117:18)
     at ToolbarFocusableComponent.componentDidMount (node_modules/reakit/lib/Toolbar.js:198:35)
     at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9411:22)
     at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10808:7)
     at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2377:14)
     at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
     at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
     at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
     at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
     at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
     at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2427:16)
     at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
     at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11020:7)
     at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12471:5
     at Object.unstable_runWithPriority (node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:255:12)
     at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12470:13)
     at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12399:9)
     at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12307:7)
     at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12281:3)
     at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12150:5)
     at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11965:5)
     at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12564:3)
     at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12592:10)
     at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12603:10)
     at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13036:5)
     at Object.create (src/components/__tests__/toolbar.js:9:26)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Test file:
```js
import React from 'react'
import renderer from 'react-test-renderer'
import { Toolbar } from 'reakit'

const MyToolbar = () => (
  <Toolbar>
    <Toolbar.Content whiteSpace="nowrap">
      <Toolbar.Focusable>Im focusable</Toolbar.Focusable>
      <div>Im not</div>
      <Toolbar.Focusable>Use arrow keys</Toolbar.Focusable>
    </Toolbar.Content>
  </Toolbar>
)

describe('toolbar', () => {
  it('renders correctly', () => {
    const tree = renderer.create(<MyToolbar />).toJSON()
    expect(tree).toMatchSnapshot()
  });
})
```

**What is the expected behavior?**

It should create the `tree` in order to able unit testing.

**Other relevant information:**
```
{
    "reakit": "0.16.0",
    "babel-jest": "24.5.0",
    "jest": "24.5.0",
    "react-test-renderer": "16.8.4"
}
```

**Comment by diegohaz** [comment] 2019-03-14 17:12
Hi @luizcieslak

Could you please run `yarn why jsdom` (or an npm equivalent)?

**Comment by luizcieslak** [comment] 2019-03-14 17:29
sure!

```
yarn why jsdom
yarn why v1.13.0
[1/4] Why do we have the module "jsdom"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "jsdom@11.12.0"
info Reasons this module exists
   - "jest#jest-cli#jest-config#jest-environment-jsdom" depends on it
   - Hoisted from "jest#jest-cli#jest-config#jest-environment-jsdom#jsdom"
Done in 26.13s.
```

by the way, I'm using gatsby and was reproduced this [unit testing guide](https://www.gatsbyjs.org/docs/unit-testing/)

**Comment by diegohaz** [comment] 2019-03-14 17:38
Hmm, according to https://github.com/jsdom/jsdom/issues/1555#issuecomment-413995713, it seems that support for `Element.prototype.closest` was added in `v11.12.0` (which is the one you have installed).

I'd try to upgrade `jsdom` just in case. You can either use [`jest-environment-jsdom-thirteen`](https://github.com/theneva/jest-environment-jsdom-thirteen) or `yarn resolutions`:
```json
// in package.json
"resolutions": {
  "jsdom": "14.0.0"
}
```

**Comment by luizcieslak** [comment] 2019-03-14 18:45
same error :/

```
yarn why jsdom
yarn why v1.13.0
[1/4] Why do we have the module "jsdom"...?
[2/4] Initialising dependency graph...
warning Resolution field "jsdom@14.0.0" is incompatible with requested version "jsdom@^11.5.1"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "jsdom@14.0.0"
info Reasons this module exists
   - "jest#jest-cli#jest-config#jest-environment-jsdom" depends on it
   - Hoisted from "jest#jest-cli#jest-config#jest-environment-jsdom#jsdom"
Done in 1.90s.
```

Could you reproduce the error? Idk if it is something specific to this project.

**Comment by diegohaz** [comment] 2019-03-14 18:49
I can't. We also have [tests](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Toolbar/__tests__/ToolbarFocusable-test.tsx) on this component and everything works fine.

**Comment by diegohaz** [comment] 2019-05-14 22:17
Cleaning up issues. Closing this as we can't reproduce it. If someone has this problem and can come up with a repo or sandbox reproducing the problem, please comment here or open a new issue so we can find a solution.

**Closed by diegohaz** 2019-05-14 22:17 UTC
Labels: can't reproduce
