### ISSUE TITLE
Add ability to customize popperjs options in usePopover

### ISSUE THREAD

**Issue by anuraghazra** [reakit/reakit#758] opened 2020-10-07 07:07 UTC
## 🚀 Feature request

Currently usePopover hook only exposes the `placement`, `fixed`, `flip`, `offset` options to customize the Popperjs, but it would be useful if reakit allows us to add user defined modifiers & let us customize all the popperjs options. 

### Motivation

We are currently building a datepicker component  at work where we wanted to have "center" placement on mobile devices for the popover but could not do it since reakit does not allows us to customize the options, yes we could overwrite the CSS but that seems hacky and not optimal.

Centering popperjs: 
https://github.com/popperjs/popper-core/issues/642
https://github.com/popperjs/popper-core/pull/530

### Example

Maybe we can approach API like this

This should retain the default behaviours and just ...spread the options on top of it.

```js
  const popover = usePopoverState({
    modal: true,
    popperOptions: {...}
  });
```

or providing a popper instance directly, this would totally overwrite the default behaviours

```js
  const popover = usePopoverState({
    modal: true,
    popper: createPopper(...)
  });
```

### Possible implementations

This is how chakra implements it let's users add new modifiers and other core options: 
https://github.com/chakra-ui/chakra-ui/blob/develop/packages/popper/src/use-popper.ts

If possible, describe how this feature could be implemented. See [CONTRIBUTING.md](https://github.com/reakit/reakit/blob/master/CONTRIBUTING.md).

**Comment by tom-sherman** [comment] 2020-10-07 07:45
I believe this is a duplicate of #606

**Closed** 2020-10-07 21:59 UTC
Labels: duplicate
