### ISSUE TITLE
Slate JS (editor) inside a Reakit portal throws "Unable to find DocumentOrShadowRoot"

### ISSUE THREAD

**Issue by ratiofu** [reakit/reakit#880] opened 2021-06-12 22:18 UTC
### Current behavior

I am trying to render a [Slate editor](https://docs.slatejs.org/) inside a [Reakit Portal](https://reakit.io/docs/portal/). When doing so, I get an exception:

```
Unable to find DocumentOrShadowRoot for editor element: [object HTMLDivElement]
```

### Steps to reproduce the bug

1. [Open this reproduction sandbox](https://codesandbox.io/s/slate-reakit-portal-bug-gszn2?file=/src/index.js)

### Expected behavior

In this particular example, I should see some text I can edit, inside a grey border.

### Possible solutions

I don't have a solution, but made the following observation: Inside [slate-react's `findDocumentOrShadowRoot` method](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/plugin/react-editor.ts#L105), the editor's DOM element has the `div.__reakit-portal` as its "root" (see [`getRootNode()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode)) which in turn _seems to not be attached to the DOM_ at the time this method runs (has no parent).

~~I am not sure if this is a Slate or Reakit bug, so I am cross-posting.~~

Edit: [There's already an issue open for this in Slate](https://github.com/ianstormtaylor/slate/issues/4267), which also provides a work-around: delay rendering the editor itself until the component fully mounted (I used an effect and a local state).

### Environment

(CodeSandbox reproduction above)

**Comment by diegohaz** [comment] 2021-06-14 09:21
Thanks for opening the issue and for the reproduction @ratiofu!

I'm going to close this issue because it does seem to be a bug on Slate, not on Reakit. I can reproduce the same error with other libraries like Chakra UI: https://codesandbox.io/s/slate-with-chakra-uis-portal-worjd?file=/src/App.tsx

**Closed by diegohaz** 2021-06-14 09:21 UTC
Labels: potential bug
